name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Ensure proper line endings and download wrapper
      run: |
        sed -i 's/\r$//' gradlew
        chmod +x gradlew
        mkdir -p gradle/wrapper
        curl -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v8.5.0/gradle/wrapper/gradle-wrapper.jar
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KillingGame-Artifacts
        path: build/libs/ 