name: Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Refresh dependencies and build
        run: |
          ./gradlew --refresh-dependencies
          ./gradlew clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: killinggame-mod-artifacts
          path: build/libs/*.jar 